### ISSUE TITLE
Request: Documentation for installation

### ISSUE THREAD

**Issue by davidmrau** [castorini/anserini-embeddings#8]
I am having trouble to get the embedding code to run. Do I need to interleave this repo with the main anserini repo to compile it with maven? Could you please help me out with a short description of the installation?

**Comment by lintool** [comment]
I believe this code base is no longer being maintained, and has been superseded by https://github.com/castorini/anserini/blob/master/docs/approximate-nearestneighbor.md

cc/ @tteofili

**Comment by davidmrau** [comment]
Ok Thanks!

**Comment by tteofili** [comment]
confirmed, Anserini's approximate nearest neighbor tooling should be used instead.
